# General settings
fullnameOverride: superset
image:
  repository: apache/superset
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  nodePort:
    # -- (int)
    http: 30088

supersetNode:
  replicas:
    enabled: true
    replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi

supersetWorker:
  replicas:
    enabled: true
    replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

bootstrapScript: |
  #!/bin/bash
  pip install psycopg2-binary \
  pinotdb &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

configOverrides:
  secret: |
    SECRET_KEY = ''

persistence:
  enabled: true
  size: 2Gi
  accessMode: ReadWriteOnce
  storageClass: local-path

postgresql:
  primary:
    persistence:
      storageClass: local-path