# General settings
fullnameOverride: superset
image:
  repository: apache/superset
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  nodePort:
    # -- (int)
    http: 30088

supersetNode:
  replicas:
    enabled: true
    replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi

supersetWorker:
  replicas:
    enabled: true
    replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

bootstrapScript: |
  #!/bin/bash
  pip install psycopg2-binary \
  pinotdb &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

configOverrides:
  secret: |
    SECRET_KEY = ''


postgresql:
  primary:
    persistence:
      storageClass: standard

extraConfigs:
  import_datasources.yaml: |
    databases:
    - database_name: pinot
      sqlalchemy_uri: pinot+http://pinot-broker.pinot:8099/query?controller=http://pinot-controller.pinot:9000
      allow_csv_upload: false
      expose_in_sqllab: true